### ISSUE TITLE
Remove eslintConfig section in package.json of released func.

### ISSUE THREAD

**Issue by LucasIcarus** [unix/func#23]
# Feature request 🚀

### Arguments

VSCode Typescript Def Jump to func code will trigger eslint error like this... 

```bash
[Info  - 9:07:43 PM] ESLint server is running.
(node:44343) UnhandledPromiseRejectionWarning: Error: Failed to load config "eslint-config-ts-lambdas" to extend from.
Referenced from: /Volumes/Code/xxxxx/node_modules/func/package.json
```

Remove the eslintConfig section in `package.json` before release seems better? 

Or this section been kept for some other reasons?

**Comment by LucasIcarus** [comment]
维特聚聚贴贴

**Comment by unix** [comment]
通过 `npm init func` 创建的模板已经更新过了，现在默认不会携带 `eslint`。

**Comment by LucasIcarus** [comment]
维特聚聚稳
